backend/controllers/AddonsController.php
<?php

namespace backend\controllers;

use Yii;
use yii\data\Pagination;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\web\UnauthorizedHttpException;
use common\helpers\Url;
use common\enums\AppEnum;
use common\helpers\Auth;
use common\models\common\Addons;
use common\helpers\AddonHelper;
use common\models\wechat\Rule;
use common\enums\StatusEnum;
use common\helpers\ArrayHelper;
use common\helpers\ResultDataHelper;
use common\helpers\StringHelper;
use common\models\wechat\RuleKeyword;
use backend\modules\wechat\forms\RuleForm;

/**
 * Class AddonsController
 * @package backend\controllers
 * @author 原创脉冲 <QQ：2790684490>
 */
class AddonsController extends Controller
{
    /**
     * @var string
     */
    public $layout = "@backend/views/layouts/addon";

    /**
     * 当前路由
     *
     * @var
     */
    public $route;

    /**
     * 模块名称
     *
     * @var
     */
    public $addonName;

    public function init()
    {
        parent::init();
        $this->addonName = Yii::$app->request->get('addon', Yii::$app->request->post('addon', ''));
        $this->addonName = StringHelper::strUcwords($this->addonName);

        Yii::$app->params['inAddon'] = true;
    }

    /**
     * @param $action
     * @return bool|\yii\web\Response
     * @throws NotFoundHttpException
     * @throws UnauthorizedHttpException
     * @throws \yii\web\BadRequestHttpException
     */
    public function beforeAction($action)
    {
        if (Yii::$app->user->isGuest) {
            throw new UnauthorizedHttpException('未登录');
        }

        // 验证是否超级管理员或空权限
        if ($action->id == 'blank') {
            throw new NotFoundHttpException('找不到可用菜单，请检查自己的配置或者联系管理员');
        }

        // 权限校验
        $route = '';
        in_array($action->id, ['cover']) && $route = Addons::AUTH_COVER;
        in_array($action->id, ['rule', 'rule-edit', 'rule-delete', 'ajax-update']) && $route = Addons::AUTH_RULE;
        if (false === Auth::verify($route)) {
            throw new UnauthorizedHttpException('对不起，您现在还没获此操作的权限');
        }

        return parent::beforeAction($action);
    }

    /**
     * 导航入口
     *
     * @return string
     * @throws NotFoundHttpException
     * @throws \yii\base\InvalidConfigException
     */
    public function actionCover()
    {
        // 初始化模块
        AddonHelper::initAddon($this->addonName, $this->route);

        $covers = [];
        $baseCover = Yii::$app->params['addonBinding']['cover'];

        foreach ($baseCover as $value) {
            $key = AppEnum::$listExplain[$value['app_id']] . '入口';
            $value['url'] = '';

            !is_array($value['params']) && $value['params'] = [];
            $route = ArrayHelper::merge([$value['route']], $value['params']);
            switch ($value['app_id']) {
                case AppEnum::API :
                    $value['url'] = Url::toApi($route);
                    break;
                case AppEnum::FRONTEND :
                    $value['url'] = Url::toFront($route);
                    break;
                case AppEnum::WECHAT :
                    $value['url'] = Url::toWechat($route);
                    break;
                case AppEnum::OAUTH2 :
                    $value['url'] = Url::toOAuth2($route);
                    break;
                case AppEnum::STORAGE:
                    $value['url'] = Url::toStorage($route);
                    break;
            }

            $covers[$key][] = $value;
        }

        return $this->render('@backend/views/addons/cover', [
            'covers' => $covers
        ]);
    }

    /**
     * 规则
     *
     * @return string
     * @throws \yii\web\NotFoundHttpException
     */
    public function actionRule()
    {
        // 初始化模块
        AddonHelper::initAddon($this->addonName, $this->route);

        $keyword = Yii::$app->request->get('keyword', null);
        $data = Rule::find()
            ->where(['>=', 'status', StatusEnum::DISABLED])
            ->andWhere(['module' => Rule::RULE_MODULE_ADDON])
            ->andFilterWhere(['merchant_id' => Yii::$app->services->merchant->getId()])
            ->andFilterWhere(['like', 'name', $keyword]);

        $pages = new Pagination(['totalCount' => $data->count(), 'pageSize' => 10]);
        $models = $data->offset($pages->offset)
            ->orderBy('sort asc,created_at desc')
            ->with('ruleKeyword')
            ->limit($pages->limit)
            ->all();

        return $this->render('@backend/views/addons/rule', [
            'models' => $models,
            'addonName' => $this->addonName,
            'pages' => $pages,
            'keyword' => $keyword,
        ]);
    }

    /**
     * 规则编辑
     *
     * @return string|\yii\web\Response
     * @throws NotFoundHttpException
     * @throws \yii\base\ExitException
     */
    public function actionRuleEdit()
    {
        // 初始化模块
        AddonHelper::initAddon($this->addonName, $this->route);

        $request = Yii::$app->request;
        $id = $request->get('id');
        $model = $this->findModel($id);
        $model->module = Rule::RULE_MODULE_ADDON;
        $model->data = $this->addonName;
        $defaultRuleKeywords = Yii::$app->services->wechatRuleKeyword->getType($model->ruleKeyword);

        // ajax校验
        if (Yii::$app->request->isAjax && !Yii::$app->request->isPjax) {
            if ($model->load(Yii::$app->request->post())) {
                Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
                Yii::$app->response->data = \yii\widgets\ActiveForm::validate($model);
                Yii::$app->end();
            }
        }

        $postData = Yii::$app->request->post();
        if ($model->load($postData)) {
            $transaction = Yii::$app->db->beginTransaction();

            try {
                if (!$model->save()) {
                    throw new \Exception(Yii::$app->debris->analyErr($model->getFirstErrors()));
                }

                // 全部关键字
                $ruleKey = $postData['ruleKey'] ?? [];
                $ruleKey[RuleKeyword::TYPE_MATCH] = explode(',', $model->keyword);
                // 更新关键字
                Yii::$app->services->wechatRuleKeyword->update($model, $ruleKey, $defaultRuleKeywords);
                $transaction->commit();

                return $this->redirect(['/addons/rule', 'addon' => $this->addonName]);
            } catch (\Exception $e) {
                $transaction->rollBack();
                Yii::$app->getSession()->setFlash('error', $e->getMessage());
                return $this->redirect(['/addons/rule', 'addon' => $this->addonName]);
            }
        }

        return $this->render('@backend/views/addons/rule-edit', [
            'model' => $model,
            'ruleKeywords' => $defaultRuleKeywords,
        ]);
    }

    /**
     * 删除
     *
     * @param $id
     * @return mixed
     * @throws \Throwable
     * @throws yii\db\StaleObjectException
     */
    public function actionRuleDelete($id)
    {
        $model = $this->findModel($id);
        if ($model->delete()) {
            return $this->redirect(['/addons/rule', 'addon' => $this->addonName]);
        }

        Yii::$app->getSession()->setFlash('error', '删除失败');
        return $this->redirect(['/addons/rule', 'addon' => $this->addonName]);
    }

    /**
     * 更新排序/状态字段
     *
     * @param $id
     * @return array
     */
    public function actionAjaxUpdate($id)
    {
        if (!($model = Rule::find()->where(['id' => $id])->andWhere(['merchant_id' => Yii::$app->services->merchant->getId()])->one())) {
            return ResultDataHelper::json(404, '找不到数据');
        }

        $model->attributes = ArrayHelper::filter(Yii::$app->request->get(), ['sort', 'status']);
        if (!$model->save()) {
            return ResultDataHelper::json(422, Yii::$app->debris->analyErr($model->getFirstErrors()));
        }

        return ResultDataHelper::json(200, '修改成功');
    }

    /**
     * 返回模型
     *
     * @param $id
     * @return mixed
     */
    protected function findModel($id)
    {
        if (empty($id) || empty(($model = RuleForm::find()->where(['id' => $id])->andWhere(['merchant_id' => Yii::$app->services->merchant->getId()])->one()))) {
            $model = new RuleForm();
            return $model->loadDefaultValues();
        }

        return $model;
    }
}

common/controllers/AddonsController.php
<?php

namespace common\controllers;

use Yii;
use yii\web\Controller;
use common\helpers\AddonHelper;
use common\helpers\StringHelper;
use common\helpers\Url;
use common\enums\AppEnum;
use common\components\BaseAction;

/**
 * 模块基类控制器
 *
 * Class AddonsController
 * @package common\controllers
 * @author 原创脉冲 <QQ：2790684490>
 */
class AddonsController extends Controller
{
    use BaseAction;

    /**
     * 视图自动加载文件路径
     *
     * @var string
     */
    public $layout = null;

    /**
     * 是否钩子
     *
     * @var bool
     */
    public $isHook = false;

    /**
     * @throws \yii\base\InvalidConfigException
     */
    public function init()
    {
        parent::init();

        // 后台视图默认载入模块视图
        if (!$this->layout) {
            $this->layout = '@' . Yii::$app->id . '/views/layouts/main';

            if (Yii::$app->id == AppEnum::BACKEND) {
                $this->layout = '@' . Yii::$app->id . '/views/layouts/addon';
            }
        }
    }

    /**
     * @param string $view
     * @param array $params
     * @return string
     */
    public function render($view, $params = [])
    {
        $content = $this->getView()->render($this->analyView($view), $params, $this);
        return $this->renderContent($content);
    }

    /**
     * @param string $view
     * @param array $params
     * @return string
     */
    public function renderPartial($view, $params = [])
    {
        return $this->getView()->render($this->analyView($view), $params, $this);
    }

    /**
     * @param string $view
     * @param array $params
     * @return string
     */
    public function renderAjax($view, $params = [])
    {
        return $this->getView()->renderAjax($this->analyView($view), $params, $this);
    }

    /**
     * 跳转
     *
     * @param array|string $url
     * @param int $statusCode
     * @return \yii\console\Response|\yii\web\Response
     */
    public function redirect($url, $statusCode = 302)
    {
        return Yii::$app->getResponse()->redirect(Url::to($url), $statusCode);
    }

    /**
     * 匹配对应的渲染的视图
     *
     * @param $view
     */
    protected function analyView($view)
    {
        // 判断是否有自定义的路径
        if (strncmp($view, '@', 1) === 0) {
            return $view;
        }

        // 判断路由是否写全
        $controller = '';
        if (count(explode('/', $view)) == 1) {
            $controller = StringHelper::toUnderScore(Yii::$app->params['addonInfo']['controller']) . '/';
        }

        $appId = $this->isHook == true ? 'backend' : Yii::$app->id;
        return "@addons" . '/' . Yii::$app->params['addonInfo']['name'] . '/' . $appId . '/views/' . $controller . $view;
    }

    /**
     * 获取配置信息
     *
     * @return mixed
     */
    protected function getConfig()
    {
        return AddonHelper::getConfig();
    }

    /**
     * 写入配置信息
     *
     * @param $config
     * @return bool
     */
    protected function setConfig($config)
    {
        return AddonHelper::setConfig($config);
    }
}

backend/views/addons/blank.php
<?php

backend/views/addons/cover.php
<?php

use common\helpers\Html;
use common\helpers\StringHelper;

$this->title = '应用入口';
$this->params['breadcrumbs'][] = $this->title;

$addon = Yii::$app->params['addon']['name'];
$addon = StringHelper::toUnderScore($addon);

$active = '';
$i = 1;
?>

<!--jq二维码生成-->
<?= Html::jsFile('@web/resources/plugins/jquery-qrcode/jquery.qrcode.min.js'); ?>
<?= Html::jsFile('@web/resources/plugins/clipboard/clipboard.min.js'); ?>

<div class="row">
    <div class="col-sm-12">
        <div class="nav-tabs-custom">
            <ul class="nav nav-tabs">
                <?php foreach ($covers as $key => $value) { ?>
                    <li class="<?= empty($active) ? 'active' : ''; ?>"><a data-toggle="tab" href="#tab-<?= $key ?>"
                                                                          aria-expanded="true"><?= Html::encode($key) ?></a></li>
                    <?php if (!$active) {
                        $active = $key;
                    } ?>
                <?php } ?>
            </ul>
            <div class="tab-content rf-auto">
                <?php foreach ($covers as $key => $value) { ?>
                    <?php $i++; ?>
                    <div class="<?= $active == $key ? 'active' : ''; ?> tab-pane" id="tab-<?= $key ?>">
                        <?php foreach ($value as $item) { ?>
                            <div class="col-sm-12">
                                <div class="form-group">
                                    <label class="control-label" for="menu-title"><?= Html::encode($item['title']); ?></label>
                                    <div class="input-group m-b">
                                        <input id="<?= $key . $i ?>" class="form-control" type="text" value="<?= $item['url'] ?>" readonly>
                                        <span class="input-group-btn">
                                            <button class="btn btn-white" data-clipboard-target="#<?= $key . $i ?>">复制链接</button>
                                        </span>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <label class="control-label" for="menu-title">二维码</label><br>
                                    <div class="row m-l-none">
                                        <div data-src="<?= $item['url']; ?>" class="rf-qr-p"></div>
                                    </div>
                                </div>
                                <div class="hr-line-dashed"></div>
                            </div>
                        <?php } ?>
                    </div>
                <?php } ?>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $('.rf-qr-p').each(function (letter, rows) {
            $(rows).qrcode({
                text: $(rows).data('src'),
                width: 150,
                height: 150,
            });
        })

        var clipboard = new ClipboardJS('.btn');

        clipboard.on('success', function(e) {
            console.info('Action:', e.action);
            console.info('Text:', e.text);
            console.info('Trigger:', e.trigger);

            e.clearSelection();
            rfMsg('复制成功');
        });

        clipboard.on('error', function(e) {
            console.error('Action:', e.action);
            console.error('Trigger:', e.trigger);
            rfMsg(e.trigger)
        });
    });
</script>

backend/views/addons/rule.php
<?php
use yii\widgets\LinkPager;
use yii\widgets\ActiveForm;
use yii\helpers\Url;
use yii\helpers\Html;
use common\models\wechat\RuleKeyword;
use common\enums\StatusEnum;

$this->title = '规则回复';
$this->params['breadcrumbs'][] = ['label' => $this->title];
?>

<div class="row">
    <div class="col-sm-12">
        <div class="nav-tabs-custom">
            <div class="box-header">
                <h3 class="box-title"><?= $this->title; ?></h3>
                <div class="box-tools">
                    <?= Html::a('<i class="fa fa-plus"></i> 创建', ['/addons/rule-edit', 'addon' => $addonName], [
                        'class' => 'btn btn-primary btn-xs'
                    ]) ?>
                </div>
            </div>
            <div class="tab-content">
                <div class="active tab-pane">
                    <div class="row">
                        <div class="col-sm-4">
                            <?php $form = ActiveForm::begin([
                                'action' => Url::to(['/addons/rule', 'addon' => $addonName]),
                                'method' => 'get'
                            ]); ?>
                            <div class="input-group m-b">
                                <?= Html::textInput('keyword', $keyword, [
                                    'placeholder' => '请输入规则',
                                    'class' => 'form-control'
                                ])?>
                                <?= Html::tag('span', '<button class="btn btn-white"><i class="fa fa-search"></i> 搜索</button>', ['class' => 'input-group-btn'])?>
                            </div>
                            <?php ActiveForm::end(); ?>
                        </div>
                    </div>
                    <?php foreach($models as $model){ ?>
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <span class="collapsed"><?= $model->name ?></span>
                                <span class="pull-right" id="<?= $model->id ?>">
                                    <span class="label label-info">优先级：<?= $model->sort; ?></span>
                                    <?php if(Yii::$app->services->wechatRuleKeyword->verifyTake($model->ruleKeyword)){ ?>
                                        <span class="label label-info">直接接管</span>
                                    <?php } ?>
                                    <?php if($model->status == StatusEnum::ENABLED){ ?>
                                        <span class="label label-info pointer" onclick="statusRule(this)">已启用</span>
                                    <?php }else{ ?>
                                        <span class="label label-danger pointer" onclick="statusRule(this)">已禁用</span>
                                    <?php } ?>
                                </span>
                            </div>
                            <div id="collapseOne" class="panel-collapse collapse in" aria-expanded="true" style="">
                                <div class="panel-body">
                                    <div class="col-lg-9 tooltip-demo">
                                        <?php if($model->ruleKeyword){ ?>
                                            <?php foreach($model->ruleKeyword as $rule){
                                                if($rule->type != RuleKeyword::TYPE_TAKE){ ?>
                                                    <span class="label label-default" data-toggle="tooltip" data-placement="bottom" title="<?= RuleKeyword::$typeExplain[$rule->type]; ?>"><?= $rule->content?></span>
                                                <?php }
                                            }
                                        } ?>
                                    </div>
                                    <div class="col-lg-3">
                                        <div class="btn-group pull-right">
                                            <a class="btn btn-white btn-sm" href="<?= Url::to(['/addons/rule-edit', 'addon' => $addonName, 'id' => $model->id]); ?>"><i class="fa fa-edit"></i> 编辑</a>
                                            <a class="btn btn-white btn-sm" href="<?= Url::to(['/addonsrule-delete', 'addon' => $addonName, 'id' => $model->id]); ?>" onclick="rfDelete(this);return false;"><i class="fa fa-times"></i> 删除</a>
                                            <!-- <a class="btn btn-white btn-sm" href="#"><i class="fa fa-bar-chart-o"></i> 使用率走势</a>-->
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <?php } ?>
                    <div class="row">
                        <div class="col-sm-12">
                            <?= LinkPager::widget([
                                'pagination' => $pages,
                            ]);?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    // status => 1:启用;-1禁用;
    function statusRule(obj){
        var id = $(obj).parent().attr('id');
        var self = $(obj);
        var status = self.hasClass("label-danger") ? 1 : 0;

        $.ajax({
            type:"get",
            url:"<?= Url::to(['/addons/ajax-update'])?>",
            dataType: "json",
            data: {id:id,status:status},
            success: function(data){
                if(data.code == 200) {
                    if(self.hasClass("label-danger")){
                        self.removeClass("label-danger").addClass("label-info");
                        self.text('已启用');
                    } else {
                        self.removeClass("label-info").addClass("label-danger");
                        self.text('已禁用');
                    }
                }else{
                    alert(data.message);
                }
            }
        });
    }
</script>